// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Zoologico.API.Migrations
{
    [DbContext(typeof(ZoologicoAPIContext))]
    partial class ZoologicoAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zoologico.Modelos.Tarea.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Edad")
                        .HasColumnType("integer");

                    b.Property<int?>("EspecieCodigo")
                        .HasColumnType("integer");

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .HasColumnType("text");

                    b.Property<int?>("RazaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EspecieCodigo");

                    b.HasIndex("RazaId");

                    b.ToTable("Animales");
                });

            modelBuilder.Entity("Zoologico.Modelos.Tarea.Especie", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("NombreComun")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("Zoologico.Modelos.Tarea.Raza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Razas");
                });

            modelBuilder.Entity("Zoologico.Modelos.Tarea.Animal", b =>
                {
                    b.HasOne("Zoologico.Modelos.Tarea.Especie", "Especie")
                        .WithMany("Animales")
                        .HasForeignKey("EspecieCodigo");

                    b.HasOne("Zoologico.Modelos.Tarea.Raza", "Raza")
                        .WithMany("Animales")
                        .HasForeignKey("RazaId");

                    b.Navigation("Especie");

                    b.Navigation("Raza");
                });

            modelBuilder.Entity("Zoologico.Modelos.Tarea.Especie", b =>
                {
                    b.Navigation("Animales");
                });

            modelBuilder.Entity("Zoologico.Modelos.Tarea.Raza", b =>
                {
                    b.Navigation("Animales");
                });
#pragma warning restore 612, 618
        }
    }
}
